uri_config = '/config'
uri_get_all = '/weather/all'
uri_get_location = '/weather/location'
uri_get_weather_forecast = '/weather/forecast/<option>'
uri_get_weather_sunrisesunset = '/weather/sunrise-sunset/<date>'
